// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.1
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _tansig_HH_
#define _tansig_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "tansig_fmul_32ns_32ns_32_4_max_dsp.h"
#include "tansig_fptrunc_64ns_32_3.h"
#include "tansig_fpext_32ns_64_3.h"
#include "tansig_dadd_64ns_64ns_64_5_full_dsp.h"
#include "tansig_ddiv_64ns_64ns_64_31.h"
#include "tansig_dexp_64ns_64ns_64_18_full_dsp.h"

namespace ap_rtl {

struct tansig : public sc_module {
    // Port declarations 9
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > data;
    sc_out< sc_lv<32> > result;
    sc_out< sc_logic > result_ap_vld;


    // Module declarations
    tansig(sc_module_name name);
    SC_HAS_PROCESS(tansig);

    ~tansig();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    tansig_fmul_32ns_32ns_32_4_max_dsp<0,4,32,32,32>* tansig_fmul_32ns_32ns_32_4_max_dsp_U0;
    tansig_fptrunc_64ns_32_3<1,3,64,32>* tansig_fptrunc_64ns_32_3_U1;
    tansig_fpext_32ns_64_3<2,3,32,64>* tansig_fpext_32ns_64_3_U2;
    tansig_dadd_64ns_64ns_64_5_full_dsp<3,5,64,64,64>* tansig_dadd_64ns_64ns_64_5_full_dsp_U3;
    tansig_ddiv_64ns_64ns_64_31<4,31,64,64,64>* tansig_ddiv_64ns_64ns_64_31_U4;
    tansig_dexp_64ns_64ns_64_18_full_dsp<5,18,64,64,64>* tansig_dexp_64ns_64ns_64_18_full_dsp_U5;
    sc_signal< sc_lv<7> > ap_CS_fsm;
    sc_signal< sc_lv<64> > grp_fu_51_p2;
    sc_signal< sc_lv<64> > reg_67;
    sc_signal< sc_lv<32> > grp_fu_38_p2;
    sc_signal< sc_lv<32> > tmp_reg_78;
    sc_signal< sc_lv<64> > grp_fu_48_p1;
    sc_signal< sc_lv<64> > tmp_1_reg_83;
    sc_signal< sc_lv<64> > grp_fu_62_p2;
    sc_signal< sc_lv<64> > tmp_2_reg_88;
    sc_signal< sc_lv<64> > grp_fu_57_p2;
    sc_signal< sc_lv<64> > tmp_4_reg_93;
    sc_signal< sc_lv<32> > grp_fu_44_p1;
    sc_signal< sc_lv<32> > grp_fu_38_p0;
    sc_signal< sc_lv<32> > grp_fu_38_p1;
    sc_signal< sc_lv<64> > grp_fu_44_p0;
    sc_signal< sc_lv<32> > grp_fu_48_p0;
    sc_signal< sc_lv<64> > grp_fu_51_p0;
    sc_signal< sc_lv<64> > grp_fu_51_p1;
    sc_signal< sc_lv<64> > grp_fu_57_p0;
    sc_signal< sc_lv<64> > grp_fu_57_p1;
    sc_signal< sc_lv<64> > grp_fu_62_p1;
    sc_signal< sc_logic > grp_fu_38_ce;
    sc_signal< sc_logic > grp_fu_44_ce;
    sc_signal< sc_logic > grp_fu_48_ce;
    sc_signal< sc_logic > grp_fu_51_ce;
    sc_signal< sc_logic > grp_fu_57_ce;
    sc_signal< sc_lv<64> > grp_fu_62_p0;
    sc_signal< sc_logic > grp_fu_62_ce;
    sc_signal< sc_lv<7> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<7> ap_ST_st1_fsm_0;
    static const sc_lv<7> ap_ST_st2_fsm_1;
    static const sc_lv<7> ap_ST_st3_fsm_2;
    static const sc_lv<7> ap_ST_st4_fsm_3;
    static const sc_lv<7> ap_ST_st5_fsm_4;
    static const sc_lv<7> ap_ST_st6_fsm_5;
    static const sc_lv<7> ap_ST_st7_fsm_6;
    static const sc_lv<7> ap_ST_st8_fsm_7;
    static const sc_lv<7> ap_ST_st9_fsm_8;
    static const sc_lv<7> ap_ST_st10_fsm_9;
    static const sc_lv<7> ap_ST_st11_fsm_10;
    static const sc_lv<7> ap_ST_st12_fsm_11;
    static const sc_lv<7> ap_ST_st13_fsm_12;
    static const sc_lv<7> ap_ST_st14_fsm_13;
    static const sc_lv<7> ap_ST_st15_fsm_14;
    static const sc_lv<7> ap_ST_st16_fsm_15;
    static const sc_lv<7> ap_ST_st17_fsm_16;
    static const sc_lv<7> ap_ST_st18_fsm_17;
    static const sc_lv<7> ap_ST_st19_fsm_18;
    static const sc_lv<7> ap_ST_st20_fsm_19;
    static const sc_lv<7> ap_ST_st21_fsm_20;
    static const sc_lv<7> ap_ST_st22_fsm_21;
    static const sc_lv<7> ap_ST_st23_fsm_22;
    static const sc_lv<7> ap_ST_st24_fsm_23;
    static const sc_lv<7> ap_ST_st25_fsm_24;
    static const sc_lv<7> ap_ST_st26_fsm_25;
    static const sc_lv<7> ap_ST_st27_fsm_26;
    static const sc_lv<7> ap_ST_st28_fsm_27;
    static const sc_lv<7> ap_ST_st29_fsm_28;
    static const sc_lv<7> ap_ST_st30_fsm_29;
    static const sc_lv<7> ap_ST_st31_fsm_30;
    static const sc_lv<7> ap_ST_st32_fsm_31;
    static const sc_lv<7> ap_ST_st33_fsm_32;
    static const sc_lv<7> ap_ST_st34_fsm_33;
    static const sc_lv<7> ap_ST_st35_fsm_34;
    static const sc_lv<7> ap_ST_st36_fsm_35;
    static const sc_lv<7> ap_ST_st37_fsm_36;
    static const sc_lv<7> ap_ST_st38_fsm_37;
    static const sc_lv<7> ap_ST_st39_fsm_38;
    static const sc_lv<7> ap_ST_st40_fsm_39;
    static const sc_lv<7> ap_ST_st41_fsm_40;
    static const sc_lv<7> ap_ST_st42_fsm_41;
    static const sc_lv<7> ap_ST_st43_fsm_42;
    static const sc_lv<7> ap_ST_st44_fsm_43;
    static const sc_lv<7> ap_ST_st45_fsm_44;
    static const sc_lv<7> ap_ST_st46_fsm_45;
    static const sc_lv<7> ap_ST_st47_fsm_46;
    static const sc_lv<7> ap_ST_st48_fsm_47;
    static const sc_lv<7> ap_ST_st49_fsm_48;
    static const sc_lv<7> ap_ST_st50_fsm_49;
    static const sc_lv<7> ap_ST_st51_fsm_50;
    static const sc_lv<7> ap_ST_st52_fsm_51;
    static const sc_lv<7> ap_ST_st53_fsm_52;
    static const sc_lv<7> ap_ST_st54_fsm_53;
    static const sc_lv<7> ap_ST_st55_fsm_54;
    static const sc_lv<7> ap_ST_st56_fsm_55;
    static const sc_lv<7> ap_ST_st57_fsm_56;
    static const sc_lv<7> ap_ST_st58_fsm_57;
    static const sc_lv<7> ap_ST_st59_fsm_58;
    static const sc_lv<7> ap_ST_st60_fsm_59;
    static const sc_lv<7> ap_ST_st61_fsm_60;
    static const sc_lv<7> ap_ST_st62_fsm_61;
    static const sc_lv<7> ap_ST_st63_fsm_62;
    static const sc_lv<7> ap_ST_st64_fsm_63;
    static const sc_lv<7> ap_ST_st65_fsm_64;
    static const sc_lv<7> ap_ST_st66_fsm_65;
    static const sc_lv<7> ap_ST_st67_fsm_66;
    static const sc_lv<7> ap_ST_st68_fsm_67;
    static const sc_lv<7> ap_ST_st69_fsm_68;
    static const sc_lv<32> ap_const_lv32_C0000000;
    static const sc_lv<64> ap_const_lv64_3FF0000000000000;
    static const sc_lv<64> ap_const_lv64_BFF0000000000000;
    static const sc_lv<64> ap_const_lv64_4000000000000000;
    static const sc_lv<64> ap_const_lv64_0;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_grp_fu_38_ce();
    void thread_grp_fu_38_p0();
    void thread_grp_fu_38_p1();
    void thread_grp_fu_44_ce();
    void thread_grp_fu_44_p0();
    void thread_grp_fu_48_ce();
    void thread_grp_fu_48_p0();
    void thread_grp_fu_51_ce();
    void thread_grp_fu_51_p0();
    void thread_grp_fu_51_p1();
    void thread_grp_fu_57_ce();
    void thread_grp_fu_57_p0();
    void thread_grp_fu_57_p1();
    void thread_grp_fu_62_ce();
    void thread_grp_fu_62_p0();
    void thread_grp_fu_62_p1();
    void thread_result();
    void thread_result_ap_vld();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
